### ISSUE TITLE
Missing Module Error

### ISSUE THREAD

**Issue by iammosespaulr** [scorelab/BellyDynamic#5]
import MultiGraph as MG
ImportError: No module named MultiGraph

  Error :solved          i made the line as from networkx.classes.multigraph import MultiGraph as MG

**Comment by agentmilindu** [comment]
@iammosespaulr Can you explain to us how you got this error? What are the steps you followed, etc?

**Comment by iammosespaulr** [comment]
i ran this command specified in the instruction python ./bellydynamic-adv/SwedenGraph.py

**Comment by iammosespaulr** [comment]
Error : 2  import NodeAttribute as NodeA
ImportError: No module named NodeAttribute

**Comment by iammosespaulr** [comment]
KInda Solved all the errors                   <----- Silly mistake
